<?php

namespace AppBundle\Repository;

/**
 * ModalItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModalItemRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllWithPortfolio() {

        $qb = $this->createQueryBuilder('mi');
        $qb->select('mi, portfolio');
        $qb->leftJoin('mi.portfolio', 'portfolio');

        return $qb->getQuery()->getResult();
    }
}
