<?php

namespace AppBundle\Repository;

/**
 * ModalItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModalItemRepository extends \Doctrine\ORM\EntityRepository
{
}
